# Generated by Django 5.2.8 on 2026-01-10 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_article_deleted_at_article_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
